# This is a basic workflow that is manually triggered to prepare the release
# It creates the merge and version PR.

name: Prepare Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  pulling-into-main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Read Current Version
      id: read-current-version
      run: |
        version=$(jq -r ".version" version.json)
        echo "::set-output name=VERSION::$version"
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: 'chore: release ${{ steps.read-current-version.outputs.VERSION }}'
        pr_body: "Pulling ${{ github.ref }} into main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "auto-pr"
  version-bump:
    runs-on: ubuntu-latest
    steps:   
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Build Next Version
      id: build-next-version
      run: |
        version=$(jq -r ".version" version.json)
        major=$(echo $version | awk '{split($0, components, "."); print components[1]}')
        minor=$(echo $version | awk '{split($0, components, "."); print components[2]}')
        echo "::set-output name=VERSION::$major.$minor"
    - name: Commit and push next version
      id: commit-push
      run: |
        git config --global user.email "github-aws-sdk-dotnet-automation@amazon.com"
        git config --global user.name "aws-sdk-dotnet-automation"
        content=$(jq -r '.version = ${{ steps.build-next-version.outputs.VERSION }}' version.json)
        echo $content
        echo $content > version.json
        branch=chore/version-bump-${{ steps.build-next-version.outputs.VERSION }}
        git checkout -b $branch
        git add version.json
        git commit -m "build: version bump to ${{ steps.build-next-version.outputs.VERSION }}"
        git push origin $branch
        echo "::set-output name=BRANCH::$branch"
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ steps.commit-push.outputs.BRANCH }}
        destination_branch: "dev"
        pr_title: "build: version bump to ${{ steps.build-next-version.outputs.VERSION }}"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "auto-pr"
